# Generated by Django 5.0.6 on 2024-06-27 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject_Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Language_1', models.IntegerField()),
                ('Language_2', models.IntegerField()),
                ('Acting', models.IntegerField()),
                ('Dance', models.IntegerField()),
            ],
        ),
    ]
