# Generated by Django 5.0.6 on 2024-06-27 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_portal', '0002_subject_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject_marks',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='student_portal.student'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='city',
            field=models.TextField(),
        ),
    ]
